version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SCIBERT_URL=http://scibert:8080

  scibert:
    build:
      context: ./scibert-master
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./scibert-master:/scibert-master
